name: healthy_fitness_pro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  bloc_concurrency: ^0.3.0

  # Route management:
  go_router: ^17.1.0

  # Network:
  dio: ^5.9.2

  # DI:
  get_it: ^9.2.1



  # intl:
  intl: any
  intl_utils:
  flutter_localizations:
    sdk: flutter

  # Utilities:
  logger: ^2.6.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  equatable: ^2.0.8
  flutter_secure_storage: ^10.0.0

  # Fonts:
  google_fonts: ^8.0.2
  font_awesome_flutter: ^11.0.0

  # Map

  # Data:
  shared_preferences: ^2.5.4
  hive: ^2.2.3

  # Presentation:
  flutter_svg: ^2.2.4
  camera: ^0.12.0
  cached_network_image: ^3.4.1
  loading_indicator: ^3.1.1
  connectivity_plus: ^7.0.0
  toastification: ^3.0.3
  workmanager: ^0.9.0+3

  # Others:
  retrofit: ^4.9.2
  rxdart: ^0.28.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3
  retrofit_generator: ^10.2.3
  json_serializable: ^6.11.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/videos/
    - assets/fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800